Repository k0sproject/rig, pull requests merged in 2024-03, with the labels that each got.

#178 Add ssh keepalive support
  protocol/ssh/connection.go
  protocol/ssh/options.go
Labels: enhancement

#177 Detect windows SSH from server header
  protocol/ssh/connection.go
  protocol/ssh/knownposix.go
Labels: enhancement

#179 Replace go-shellwords with own shellescape.Split
  go.mod
  go.sum
  protocol/localhost/connection.go
  protocol/ssh/connection.go
  sh/shellescape/split.go
  sh/shellescape/split_test.go
  sh/shellescape/unquote.go
  sh/shellescape/unquote_test.go
Labels: enhancement, go

#183 Run stat in empty env with C locale
  remotefs/posixfs.go
Labels: bug
